# Generated by Django 5.0.6 on 2025-06-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='clave',
            field=models.CharField(default='123', max_length=10),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=models.TextField(verbose_name='Acerca de: '),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(max_length=15, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Curso'),
        ),
    ]
