# Generated by Django 5.0.6 on 2025-07-16 22:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-created'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='clave',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción: '),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(max_length=15, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
